# Generated by Django 4.1.2 on 2022-10-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yao_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yaojob',
            name='id',
        ),
        migrations.AddField(
            model_name='yaojob',
            name='job_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
